# Create the sqlite database using that converted script
# and then
import sqlite3

# Connect to SQLite database (creates it if it doesn't exist)
conn = sqlite3.connect('database.db')
cursor = conn.cursor()

# Execute the schema and data insertion SQL
cursor.executescript('''
/*
 Convert this Oracle SQL database export to SQLite
 */

-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTOMER_ID    INTEGER PRIMARY KEY NOT NULL,
    NAME           TEXT NOT NULL,
    REGION         TEXT,
    STREET_ADDRESS TEXT,
    CITY           TEXT,
    STATE          TEXT,
    ZIP            INTEGER
);

-- Table: PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_ID  INTEGER PRIMARY KEY,
    DESCRIPTION TEXT,
    PRICE       REAL
);

-- Table: CUSTOMER_ORDER
CREATE TABLE CUSTOMER_ORDER (
    ORDER_ID    INTEGER PRIMARY KEY NOT NULL,
    ORDER_DATE  TEXT NOT NULL,
    SHIP_DATE   TEXT,
    CUSTOMER_ID INTEGER REFERENCES CUSTOMER (CUSTOMER_ID) NOT NULL,
    PRODUCT_ID  INTEGER REFERENCES PRODUCT (PRODUCT_ID) NOT NULL,
    ORDER_QTY   INTEGER NOT NULL,
    SHIPPED     INTEGER DEFAULT 0 NOT NULL
);

-- Inserts for CUSTOMER
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (1, 'LITE Industrial', 'Southwest', '729 Ravine Way', 'Irving', 'TX', 75014);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (2, 'Rex Tooling Inc', 'Southwest', '6129 Collie Blvd', 'Dallas', 'TX', 75201);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (3, 'Re-Barre Construction', 'Southwest', '9043 Windy Dr', 'Irving', 'TX', 75032);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (4, 'Prairie Construction', 'Southwest', '264 Long Rd', 'Moore', 'OK', 62104);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (5, 'Marsh Lane Metal Works', 'Southeast', '9143 Marsh Ln', 'Avondale', 'LA', 79782);

-- Inserts for PRODUCT
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (1, 'Copper', 7.51);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (2, 'Aluminum', 2.58);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (3, 'Silver', 15);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (4, 'Steel', 12.31);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (5, 'Bronze', 4);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (6, 'Duralumin', 7.6);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (7, 'Solder', 14.16);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (8, 'Stellite', 13.31);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (9, 'Brass', 4.75);

-- Inserts for CUSTOMER_ORDER
INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (1, '2015-05-15', '2015-05-18', 1, 1, 450, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (2, '2015-05-18', '2015-05-21', 3, 2, 600, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (3, '2015-05-20', '2015-05-23', 3, 5, 300, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (4, '2015-05-18', '2015-05-22', 5, 4, 375, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (5, '2015-05-17', '2015-05-20', 3, 2, 500, 0);
''')

# Commit changes and close connection
conn.commit()
conn.close()

print("SQLite database initialized successfully.")
