/*
 Convert this Oracle SQL database export to SQLite
 */

-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTOMER_ID    NUMBER PRIMARY KEY NOT NULL,
    NAME           VARCHAR2(255) NOT NULL,
    REGION         VARCHAR2(255),
    STREET_ADDRESS VARCHAR2(255),
    CITY           VARCHAR2(255),
    STATE          VARCHAR2(255),
    ZIP            NUMBER
);

-- Table: PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_ID  NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR2(255),
    PRICE       NUMBER(10,2)
);


-- Table: CUSTOMER_ORDER
CREATE TABLE CUSTOMER_ORDER (
    ORDER_ID    NUMBER PRIMARY KEY NOT NULL,
    ORDER_DATE  DATE NOT NULL,
    SHIP_DATE   DATE,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMER (CUSTOMER_ID) NOT NULL,
    PRODUCT_ID  NUMBER REFERENCES PRODUCT (PRODUCT_ID) NOT NULL,
    ORDER_QTY   NUMBER NOT NULL,
    SHIPPED     NUMBER(1) DEFAULT 0 NOT NULL
);

-- Inserts for CUSTOMER
-- Inserts for CUSTOMER
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (1, 'LITE Industrial', 'Southwest', '729 Ravine Way', 'Irving', 'TX', 75014);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (2, 'Rex Tooling Inc', 'Southwest', '6129 Collie Blvd', 'Dallas', 'TX', 75201);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (3, 'Re-Barre Construction', 'Southwest', '9043 Windy Dr', 'Irving', 'TX', 75032);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (4, 'Prairie Construction', 'Southwest', '264 Long Rd', 'Moore', 'OK', 62104);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP)
VALUES (5, 'Marsh Lane Metal Works', 'Southeast', '9143 Marsh Ln', 'Avondale', 'LA', 79782);

-- Inserts for PRODUCT
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (1, 'Copper', 7.51);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (2, 'Aluminum', 2.58);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (3, 'Silver', 15);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (4, 'Steel', 12.31);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (5, 'Bronze', 4);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (6, 'Duralumin', 7.6);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (7, 'Solder', 14.16);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (8, 'Stellite', 13.31);

INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, PRICE)
VALUES (9, 'Brass', 4.75);

-- Inserts for CUSTOMER_ORDER
INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (1, TO_DATE('2015-05-15', 'YYYY-MM-DD'), TO_DATE('2015-05-18', 'YYYY-MM-DD'), 1, 1, 450, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (2, TO_DATE('2015-05-18', 'YYYY-MM-DD'), TO_DATE('2015-05-21', 'YYYY-MM-DD'), 3, 2, 600, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (3, TO_DATE('2015-05-20', 'YYYY-MM-DD'), TO_DATE('2015-05-23', 'YYYY-MM-DD'), 3, 5, 300, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (4, TO_DATE('2015-05-18', 'YYYY-MM-DD'), TO_DATE('2015-05-22', 'YYYY-MM-DD'), 5, 4, 375, 0);

INSERT INTO CUSTOMER_ORDER (ORDER_ID, ORDER_DATE, SHIP_DATE, CUSTOMER_ID, PRODUCT_ID, ORDER_QTY, SHIPPED)
VALUES (5, TO_DATE('2015-05-17', 'YYYY-MM-DD'), TO_DATE('2015-05-20', 'YYYY-MM-DD'), 3, 2, 500, 0);
